name: 'democracy-enforcer'

on:
  schedule:
    - cron: '*/30 * * * *' # checks pull requests to merge every 30 minutes
  pull_request:
    types:
      - opened # for a voting opening message on a pull request

jobs:
  enforce-democracy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: deuzu/github-democrat-action@0.3.0-alpha
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }} # GitHub automatically creates the GITHUB_TOKEN secret
          voters: deuzu, not-deuzu
          # dryRun: true
          # prMinimumReviewScore: 1
          # prVotingTimeHours: 24
          # prMarkAsMegeableLabel: ready
          # prTargetBranch: main
